# On part d'une image Python légère officielle
FROM python:3.11-slim

# Installer Tesseract et les librairies système nécessaires
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && apt-get clean

# Définir le dossier de travail dans le container
WORKDIR /app

# Copier tout le dossier back-end dans /app/back-end du container
COPY back-end /app/back-end

# Installer les dépendances (en partant du requirements.txt qui est maintenant dans /app/back-end)
RUN pip install --no-cache-dir -r /app/back-end/requirements.txt

# Copier tout le code dans le container
COPY . .
EXPOSE 5000


# Commande par défaut pour lancer ton script (à adapter selon ton fichier principal)
CMD ["python", "back-end/app.py"]
