services:
  - type: web
    name: flask-api
    runtime: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: python app.py
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: PORT
        value: 5000