services:
  - type: web
    name: flask-api
    runtime: python
    buildCommand: ./build.sh
    startCommand: "gunicorn app:app"
    env: python
    region: frankfurt
    plan: free
    envVars:
      - key: PORT
        value: 5000