services:
  - type: web
    name: flask-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: PORT
        value: 5000